# Resolve react_native_pods.rb with node to allow for hoisting
react_native_pods_path = Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require react_native_pods_path

platform :ios, '15.1'
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_frameworks! :linkage => :static

target 'WoodAITUAF' do
  project 'WoodAITUAF.xcodeproj'
  config = use_native_modules!

  pod 'onnxruntime-objc', '1.24.3'
  pod 'RNFS', :path => '../node_modules/react-native-fs'


  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  target 'WoodAITUAFTests' do
    inherit! :complete
    # Pods for testing
  end

  require_relative './VisionCameraCocoaPodUtils.rb'

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('VisionCamera')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )

    set_frame_processor_swift_flag_in_example_project(installer)
  end
end
